BoardApp/urls.py
from django.urls import path
# Импортируем созданное нами представление
from .views import AdList, AdDetail, AdCreate, AdUpdate, AdDelete, UserResponseCreate, UserResponseList, UserResponseAccept, UserResponseDelete


urlpatterns = [
   # path — означает путь.
   # В данном случае путь ко всем товарам у нас останется пустым,
   # чуть позже станет ясно почему.
   # Т.к. наше объявленное представление является классом,
   # а Django ожидает функцию, нам надо представить этот класс в виде view.
   # Для этого вызываем метод as_view.
   path('ad/', AdList.as_view(), name='ad'),
   path('ad/<int:pk>', AdDetail.as_view(), name='ad_detail'),
   path('ad/create/', AdCreate.as_view(), name='ad_create'),
   path('ad/<int:pk>/edit/', AdUpdate.as_view(), name='ad_update'),
   path('ad/<int:pk>/delete/', AdDelete.as_view(), name='ad_delete'),
   path('/response/', UserResponseList.as_view(), name='response'),
   path('/<int:pk>/response/create/', UserResponseCreate.as_view(), name='response_create'),
   path('/response/<int:pk>/delete/', UserResponseDelete.as_view(), name='response_delete'),
   path('/response/<int:pk>/accept/', UserResponseAccept.as_view(), name='response_accept'),
]

callboard/urls.py
from ckeditor_uploader.views import upload, browse
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.decorators.cache import never_cache
from django.conf import settings


urlpatterns = [
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path('', include('BoardApp.urls')),
    re_path(r'^upload/', login_required(upload), name='ckeditor_upload'),
    re_path(r'^browse/', login_required(never_cache(browse)), name='ckeditor_browse'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BoardApp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from ckeditor_uploader.fields import RichTextUploadingField


class Ad(models.Model):
    TYPE = [
        ('tank', 'Танки'),
        ('heal', 'Хилы'),
        ('DD', 'ДД'),
        ('traders', 'Торговцы'),
        ('gildemasters', 'Гилдмастеры'),
        ('quest', 'Квестгиверы'),
        ('blacksmiths', 'Кузнецы'),
        ('tanners', 'Кожевники'),
        ('potion', 'Зельевары'),
        ('spellmasters', 'Мастера заклинаний'),
    ]

    author = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.CharField(max_length=12, choices=TYPE, default='tank')
    ad_time = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=255, default='Загаловок')
    text = RichTextUploadingField(blank=True, null=True)

    def __str__(self):
        return f'{self.id} : {self.title}'

    def get_absolute_url(self):
        return reverse('ad_detail', args=[str(self.id)])


class UserResponse(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    response_time = models.DateTimeField(auto_now_add=True)
    text = models.TextField(default='Текст отклика')
    ad = models.ForeignKey(Ad, on_delete=models.CASCADE)
    status = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.author}: {self.text}'

    def get_absolute_url(self):
        return reverse('response')

templates/ad.html
<!--  наследуемся от шаблона default.html -->
{% extends 'default.html' %}



<!-- Название у нас будет  -->
{% block title %}
Ad
{% endblock title %}

<!-- В контенте на странице мы выводим сам товар, идентификатор которого был передан в url -->
{% block content %}
<h3>{{ ad.title }}</h3>
<hr>
   {% if ad %}
       <table>
           <tr>
               <td>{{ ad.get_category_display }}</td>
           </tr>
           <tr>
               <td>{{ ad.text|safe}}</td>
           </tr>
           <tr>
               <td>Опубликовоно {{ ad.ad_time|date:'d.m.Y' }}. Автор :{{ ad.author }}</td>
           </tr>
       </table>
   {% else %}
       <h2>Такого поста не существует!</h2>
   {% endif %}
<hr>
   {% if ad.author != request.user and request.user.is_authenticated %}
      <a href="{% url 'response_create' ad.pk %}"><h5>Добавить отклик</h5></a>
   {% endif %}
{% endblock content %}

templates/ad_create.html
{% extends 'default.html' %}

{% block content %}
<h1>Добавит объявление:</h1>
<h1>{{object.title}}</h1>
<h1>{{object.ad_time}}</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    {{ form.media }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

templates/ad_delete.html
{% extends 'default.html' %}

{% block content %}
<h1>Удаление Объявления</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.title }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

templates/ad_edit.html
{% extends 'default.html' %}

{% block content %}
<h1>Объявление:</h1>
<h1>{{object.title}}</h1>
<h5>{{object.ad_time}}</h5>
<hr>
{% if request.user.id == object.author.id %}
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    {{ form.media }}
    <input type="submit" value="Save" />
</form>
{% else %}
<h1>Недостаточно прав! </h1>
{% endif %}
{% endblock content %}

templates/ads.html
{% extends 'default.html' %}

<!-- Название у нас будет Ad -->
{% block title %}
Ad
{% endblock title %}

<!-- В контенте на странице мы выводим все объявления -->
{% block content %}
   <h1>Все объявления</h1>
   <hr>
   {% if ads %}
       <table>
           <tr>
               <td width="400">Название</td>
               <td width="150">Дата публикации объявления</td>
               <td width="700">Описание</td>
               <td width="200">Категории</td>
               {# Условие получается составным. #}
               {% if perms.BoardApp.change_ad or perms.BoardApp.ad_delete %}
               <td width="250">Действия</td>
               {% endif %}
           </tr>
           {% for ad in ads %}
           <tr>
               <td> <a href="{% url 'ad_detail' ad.pk %}"> {{ad.title}} </a></td>
               <td>{{ ad.ad_time|date:'d.m.Y' }}</td>
               <td>{{ ad.text|safe }}</td>
               <td>{{ ad.get_category_display  }}</td>
               <td>
                    {# А здесь доступ для каждой ссылки теперь будем проверять отдельно #}
                    {% if ad.author == request.user %}
                        <a href="{% url 'ad_update' ad.pk %}">Изменить</a>
                        <a href="{% url 'ad_delete' ad.pk %}">  Удалить</a>
                    {% endif %}
                </td>
           </tr>
           {% endfor %}

       </table>
   {% else %}
       <h2>Объявлений нет!</h2>
   {% endif %}

   {# Информация о предыдущих страницах #}
   {% if page_obj.has_previous %}
       <a href="?page=1">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {# Информация о текущей странице #}
   {{ page_obj.number }}

   {# Информация о следующих страницах #}
   {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}

templates/daily_ad.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>


    <h2>Здравствуй! Новые объявления за последнюю неделю:</h2>>

    <ul>

    {% for ad in ads %}
        <li><a href="{{ link }}{{ ad.get_absolute_url }}">{{ ad.title|safe }}</a></li>
    {% endfor %}
</ul>
</body>
</html>

templates/default.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />

        {% load static %}
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
           <div class="container">
               <a class="navbar-brand" href="{%url 'ad'%}">Доска объявлений</a>
               <button class="navbar-toggler" type="button" data-toggle="collapse"
                       data-target="#navbarResponsive"
                       aria-controls="navbarResponsive" aria-expanded="false"
                       aria-label="Toggle navigation">
                   <span class="navbar-toggler-icon"></span>
               </button>
               <div class="collapse navbar-collapse" id="navbarResponsive">
                   <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                       {% if request.user.is_authenticated %}
                       <li class="nav-item"><a class="nav-link" href="{%url 'response'%}"> Отклики</a></li>
                       <li class="nav-item"><a class="nav-link" href="{%url 'ad_create'%}"> Добавить объявление</a></li>
                       <li class="nav-item"><a class="nav-link" href="/accounts/logout/">Выход {{request.user}} </a></li>
                       {% else %}
                       <li class="nav-item"><a class="nav-link" href="/accounts/login/">Вход</a></li>
                       {% endif %}
                   </ul>
               </div>
           </div>
        </nav>
       <!-- Page content-->
        <div class="container">
           <div class="row">
               <div class="col-lg-12 text-center">
                   {% block content %}
                   {% endblock content %}
               </div>
           </div>
        </div>
    </body>
</html>

templates/response.html
{% extends 'default.html' %}



<!-- Название у нас будет Ad -->
{% block title %}
Response
{% endblock title %}

<!-- В контенте на странице мы выводим все объявления -->
{% block content %}
   <h1>Отклики</h1>
   {# Добавляем форму, которая объединяет набор полей, которые будут отправляться в запросе #}
   <form action="" method="get">
       {# Переменная, которую мы передали через контекст, может сгенерировать нам форму с полями #}
       {{ filterset.form.as_p }}
       {# Добавим кнопку отправки данных формы #}
       <input type="submit" value="Найти" />
   </form>
   <hr>
   {% if responses %}
       <table>
           <tr>
               <td width="150">Объявление</td>
               <td width="700">Отклик</td>
               <td width="150">Дата создания отклика</td>
               <td width="100">Автор</td>
               <td width="250">Действия</td>
           </tr>
           {% for response in responses %}
           <tr>
               <td>{{ response.ad.title|safe }}</td>
               <td>{{ response.text|safe }}</td>
               <td>{{ response.response_time|date:'d.m.Y' }}</td>
               <td>{{ response.author  }}</td>
               <td>
                    {# А здесь доступ для каждой ссылки теперь будем проверять отдельно #}
                    {% if response.status == False %}
                        <a href="{% url 'response_accept' response.pk %}">Принять</a>
                    {% else %}
                        <q>Принято</q>
                    {% endif %}
                    <a href="{% url 'response_delete' response.pk %}">Удалить</a>
                </td>
           </tr>
           {% endfor %}

       </table>
   {% else %}
       <h2>Откликов нет!</h2>
   {% endif %}

   {# Информация о предыдущих страницах #}
   {% if page_obj.has_previous %}
       <a href="?page=1">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {# Информация о текущей странице #}
   {{ page_obj.number }}

   {# Информация о следующих страницах #}
   {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}

templates/response_create.html
{% extends 'default.html' %}

{% block content %}
<h1>Добавит отклик:</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

templates/response_delete.html
{% extends 'default.html' %}

{% block content %}
<h1>Удаление отклика</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем?"{{ object.text }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

templates/response_edit.html
{% extends 'default.html' %}

{% block content %}
<h1>Принять отклик</h1>
<h4>{{object.text}}</h4>
<h5>{{object.response_time}}</h5>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Accept" />
</form>
{% endblock content %}